name: install-armor

on:
  push:
    branches: ["*"]

jobs:
  install-armor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: Test connectivity
        run: kubectl get no
      - name: install karmor
        run: |
          make install
          sudo -u root mv karmor /usr/local/bin/
      - name: karmor install
        run : karmor install
      - name: check
        run : |
          sleep 30
          
          kubectl get pods -A
      - name: install discover-engin
        run: kubectl apply -f https://raw.githubusercontent.com/accuknox/discovery-engine/dev/deployments/k8s/deployment.yaml
      - name: install nginx
        run : |
          kubectl create ns nginx
          kubectl create deployment nginx --image=nginx:1.17.6 -n nginx

      - name: use kubearmor summary
        run : |
          sleep 10
          karmor summary -n nginx > baseline
          cat baseline

      - name: install newest nginx
        run: |
          kubectl delete deployment  nginx -n nginx
          kubectl create deployment nginx --image=nginx -n nginx

      - name: use kubearmor summary
        run : |
          sleep 10
          karmor summary -n nginx > new
          diff -r baseline new
